config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get '/contact', to: 'static_pages#contact', as: 'contact'
  get '/about(/:who)', to: 'static_pages#about', as: 'about'
  get 'users/new', to: 'users#new', as: 'register'
  post 'users/new', to: 'users#create', as: 'create_account'
  get 'users/:id', to: 'users#show', as: 'show_user'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
    @who = params[:who]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    @name = params[:name]
    @bio = params[:bio]
    puts @name
    puts @bio
    User.create(username: @name, bio: @bio)
    @id = User.last.id
    redirect_to show_user_path(id:@id)
  end

  def show
    @id = params[:id]
    @name = User.find(@id).username
    @bio = User.find(@id).bio
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>#Mates - Vivez votre passion, ensemble !</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #00815F">
      <a class="navbar-brand" href="#">#Mates</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="true" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="navbar-collapse collapse show" id="navbarColor02" style="">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item <% if current_page?('/') %>active<% end %>">
            <a class="nav-link" href="<%= root_path %>">Accueil <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item <% if current_page?(contact_path) %>active<% end %>">
            <a class="nav-link" href="<%= contact_path %>">Contact</a>
          </li>
          <li class="nav-item <% if current_page?(about_path) %>active<% end %>">
            <a class="nav-link" href="<%= about_path %>">A propos</a>
          </li>
        </ul>
        <form class="form-inline">
          <input class="form-control mr-sm-2" placeholder="Quel est votre hobby ?" aria-label="Rechercher" type="search">
          <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Go !</button>
        </form>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/static_pages/about.html.erb
<h1>A propos</h1>


<% if @who == nil %>

<p>
<form action="<%= about_path(who: 'me') %>">
<button type="submit" class="btn btn-primary">A propos de Moi</button>
</form>
</p>

<p>
<form action="<%= about_path(who: 'our_team') %>">
<button type="submit" class="btn btn-success">A propos de mon Equipe</button>
</form>
</p>

<% elsif @who == "me" %>
<p>Voici ma biographie !</p>

<% elsif @who == "our_team" %>
<p>Voici une présentation de mon groupe !</p>

<% else %>
<p>Qui es-tu ?</p>

<% end %>

app/views/static_pages/contact.html.erb
<h1>Contact</h1>

app/views/users/new.html.erb
<h1>Créer un compte</h1>

<form action="<%= create_account_path %>" method="post">
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

<p>Votre username : </p>
  <input type="text" name = "name">

<p>Votre bio : </p>
<textarea name="bio" cols="40" rows="5"></textarea>

  <input type="submit">

</form>

app/views/users/show.html.erb
<h1>Bienvenue, <%= @name %> ! Voici votre bio : </h1>
<%= @bio %>